version: 2.1
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13

      # build and push Docker image
      - run: |
          docker info
